### ISSUE TITLE
Font not found error while compiling using xelatex.

### ISSUE THREAD

**Issue by sgang007** [biswajitsc/latex-resume#1]
![screenshot from 2015-04-19 14 44 22](https://cloud.githubusercontent.com/assets/3717545/7218878/82307478-e6a2-11e4-812e-b2f7236f315c.png)
![screenshot from 2015-04-19 14 44 35](https://cloud.githubusercontent.com/assets/3717545/7218879/823a5e66-e6a2-11e4-9205-5ca46385c8df.png)

**Comment by biswajitsc** [comment]
Install Calibri font first. Free versions are available in the internet.

**Comment by sgang007** [comment]
Calibri is not available on ubuntu.
The closest type is fonts-crosextra-carlito.
I already installed that using apt-get but its not working

**Comment by biswajitsc** [comment]
In that case replace the font in the .tex file with a font that is available in your system. Calibri is not a free font. But similar fonts are available, but those might be slightly difficult to find.

Best is to replace it with a font in your system.

**Comment by sgang007** [comment]
Okay...
Should I do a pull request after I do that

Can you just leave a calibri.ttf file in your repository. It is easy to install if you have the ttf file. It is available in the windows fonts directory

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=gangulyshubhojyoti@gmail.com&idSignature=22

On Sun, Apr 19, 2015 at 4:35 PM, Biswajit Paria notifications@github.com
wrote:

> In that case replace the font in the .tex file with a font that is
> available in your system. Calibri is not a free font. But similar fonts are
> available, but those might be slightly difficult to find.
> 
> Best is to replace it with a font in your system.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/biswajitsc/latex-resume/issues/1#issuecomment-94265673
> .

## 

Shubhojyoti

**Comment by sgang007** [comment]
Never mind. I got it.
